<?php
// This is global bootstrap for autoloading

// autoload.php generated by Composer
use Doctrine\Common\Annotations\AnnotationRegistry;

//require_once dirname( __DIR__ ).'/vendor/composer/autoload_real.php';
//$loader = ComposerAutoloaderInitda9b236fb29cee79022ea8fec541840d::getLoader();
/*AnnotationRegistry::registerFile(
  dirname( __DIR__ ).'/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/DoctrineAnnotations.php'
);*/

if (!file_exists($file = __DIR__.'/../vendor/autoload.php')) {
  throw new \RuntimeException('Install the dependencies to run the test suite.');
}
$loader = require $file;
AnnotationRegistry::registerLoader(array($loader, 'loadClass'));