app_annotation:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_dashboard:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /dashboard

my:
    resource: "@MyBundle/Controller/"
    type:     annotation
    prefix:   /my/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# Sonata Media Bundle
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media