<?php

namespace AppBundle\Entity;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
  public function getFinishedTasks($projectId){
    $q = $this->createQueryBuilder('t')
      ->where('t.project = :projectId')
      ->andWhere('t.status = :completed')
      ->setParameter('projectId', $projectId)
      ->setParameter('completed', 'completed')
      ->getQuery();
    return $q->getResult();
  }
}
